### ISSUE TITLE
Error with Python3 and Python2

### ISSUE THREAD

**Issue by tecguru** [Appsolutely-Wonderful/everydollar-selenium-api#1]
Hey, thank you for putting this together. I have the same issue with a bank not supported by Everydollar. I have an API to get the transactions out of my bank but need a way to import them. 

I am running this script on a Ubuntu VM.

**When I run with Python3 I get this response:**
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.14) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/everydollar.py", line 143, in <module>
    e_dollar = EveryDollarAPI()
  File "/everydollar.py", line 43, in __init__
    opts.set_headless()
AttributeError: 'Options' object has no attribute 'set_headless'
Exception ignored in: <function EveryDollarAPI.__del__ at 0x7fe63e2b95e0>
Traceback (most recent call last):
  File "/everydollar.py", line 68, in __del__
    self.driver.close()
AttributeError: 'EveryDollarAPI' object has no attribute 'driver'

**When I run this with Python2.7 I get the following:**
Traceback (most recent call last):
  File "everydollar.py", line 11, in <module>
    from selenium import webdriver
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/__init__.py", line 18, in <module>
    from .chrome.options import Options as ChromeOptions  # noqa
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chrome/options.py", line 26
    def default_capabilities(self) -> dict:
                                   ^
SyntaxError: invalid syntax

Thank you again for your help!

**Comment by dangarbri** [comment]
Hey, it's cool that you're trying to use this!

It's meant to run in python3 so don't bother with 2.7.
kind of weird that set_headless isn't working. Selenium probably changed how you make a headless browser.

I'm using selenium 3.141.0
Try doing `python3 -m pip install selenium==3.141.0` and then running it.
You can also just comment out that line, but then you'll see the browser window open instead of having it run in the background.

**Comment by dangarbri** [comment]
It was the selenium version.
Just updated to with with the latest version of selenium.
Added `requirements.txt` for future users.

I also added a test file which has a quick example usage.
You can make a `creds.py` file with your username and password in it and then run `python test.py`
If it all works you should see a transaction show up in everydollar for $123.45 from the merchant "This is a test"

**Comment by dangarbri** [comment]
Try it out and let me know if it works for you.

**Comment by tecguru** [comment]
That worked! Thank you for putting this together and for your quick response. 

We switched to Coinbases debit card because it's paying 4% cash back but their integration with EveryDollar is broken. I am currently able to use their API to get all my transanctions with date and amount but it doesn't include the merchant name. I opened a ticket with them to see if that can be fixed. 

I have never heard of Selenium, but seems pretty powerful for things that do not have an API. I may try to understand this more and see if I can use it to scrape the merchant names off Coinbase's account page. Do you know if it can work around multi-factor auth?

**Comment by dangarbri** [comment]
Yea, selenium is a pretty cool tool for browser automation. Basically all
it does is open a web browser and click, scroll, type whatever you tell it
to.

This is the API reference for Python that I use
https://selenium-python.readthedocs.io/

I don't have a way around 2FA. But there is a semi-automatic way. What I've
been doing is turning off headless mode so the browser opens up. I have in
my code a wait that doesn't time out which waits for the page I want to
load. So when 2FA comes up, the code is waiting, then I manually enter 2FA,
then when it gets to the page the automation will pick it up.

**Comment by tecguru** [comment]
Thats great, thanks for the info and all the help!

**Comment by dangarbri** [comment]
Happy to help!
