### ISSUE TITLE
Timeout Error

### ISSUE THREAD

**Issue by tecguru** [Appsolutely-Wonderful/everydollar-selenium-api#2]
Sorry to bother you again, but I am getting the below now, any ideas?

----
Timed out waiting for page to load
Traceback (most recent call last):
  File "/home/denverm/coinbase/export-everydollar.py", line 60, in _wait_for_load
    WebDriverWait(self.driver, self.timeout).until(element_present)
  File "/home/denverm/.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/denverm/coinbase/export-everydollar.py", line 159, in <module>
    e_dollar.login('EMAIL', 'PASSWORD')
  File "/home/denverm/coinbase/export-everydollar.py", line 91, in login
    self._wait_for_load(By.CLASS_NAME, self.ADD_TRANSACTION_BTN_CLASS)
  File "/home/denverm/coinbase/export-everydollar.py", line 63, in _wait_for_load
    raise TimeoutError
TimeoutError

-----
I replaced my email and password with EMAIL and PASSWORD above.

**Comment by dangarbri** [comment]
Sometimes they put in new pop-ups that don't let it reach the transactions.
I have to keep updating it as they update their site.

You can try turning off headless mode and see what's going on.

**Comment by tecguru** [comment]
The headless mode toggle is a great tip!

It looks like the class for the add transaction button had changed, I had to update mine to this:

 ADD_TRANSACTION_BTN_CLASS = "AddTransactionLink--EjoHafiYHAtckTey
 
 It is working now, I suspect that the random string after the --- may change periodically.

**Comment by dangarbri** [comment]
Wow I can't believe they added a random string like that.

Next time it breaks I might have to search by XPath to do something like
"class starts with AddTransactionLink"
